export interface LinelistCase {
  id: string;
  outbreakId: string;
  outbreakName: string;
  outbreakSetting: string;
  outbreakType: string;
  outbreakAgent: string;
  outbreakBegan: string;
  outbreakAddress: string;
  lastName: string;
  firstName: string;
  gender: string;
  role: string;
  address: string;
  city: string;
  phone: string;
  email: string;
  buildingUnit: string;
  symptomOnset: string;
  fever: boolean;
  cough: boolean;
  sob: boolean;
  fatigue: boolean;
  headache: boolean;
  soreThroat: boolean;
  myalgia: boolean;
  chills: boolean;
  asx: boolean;
  testingStatus: string;
  testingResult: string;
  classification: string;
  currentStatus: string;
  disposition: string;
  comments: string;
}

export const LINELIST_CASES: LinelistCase[] = [
  {
    id: "case-001",
    outbreakId: "ob-001",
    outbreakName: "Sunrise Gardens LTCH",
    outbreakSetting: "LTCH",
    outbreakType: "Respiratory",
    outbreakAgent: "COVID-19",
    outbreakBegan: "2024-11-09",
    outbreakAddress: "245 Sunrise Ave, Toronto, ON M4C 1B2",
    lastName: "Smith",
    firstName: "Margaret",
    gender: "Female",
    role: "Resident",
    address: "245 Sunrise Ave",
    city: "Toronto",
    phone: "416-555-0101",
    email: "",
    buildingUnit: "Floor 3 / Room 302",
    symptomOnset: "2024-11-10",
    fever: true,
    cough: true,
    sob: false,
    fatigue: true,
    headache: false,
    soreThroat: false,
    myalgia: false,
    chills: true,
    asx: false,
    testingStatus: "Complete",
    testingResult: "Positive",
    classification: "Confirmed",
    currentStatus: "Recovered",
    disposition: "Home isolation",
    comments: "Vaccinated ×3",
  },
  {
    id: "case-002",
    outbreakId: "ob-001",
    outbreakName: "Sunrise Gardens LTCH",
    outbreakSetting: "LTCH",
    outbreakType: "Respiratory",
    outbreakAgent: "COVID-19",
    outbreakBegan: "2024-11-09",
    outbreakAddress: "245 Sunrise Ave, Toronto, ON M4C 1B2",
    lastName: "Jones",
    firstName: "Robert",
    gender: "Male",
    role: "Resident",
    address: "245 Sunrise Ave",
    city: "Toronto",
    phone: "416-555-0102",
    email: "",
    buildingUnit: "Floor 3 / Room 318",
    symptomOnset: "2024-11-11",
    fever: true,
    cough: true,
    sob: true,
    fatigue: true,
    headache: false,
    soreThroat: true,
    myalgia: true,
    chills: false,
    asx: false,
    testingStatus: "Complete",
    testingResult: "Positive",
    classification: "Confirmed",
    currentStatus: "Hospitalized",
    disposition: "Hospital transfer",
    comments: "Transferred to St. Michael's Nov 12",
  },
  {
    id: "case-003",
    outbreakId: "ob-001",
    outbreakName: "Sunrise Gardens LTCH",
    outbreakSetting: "LTCH",
    outbreakType: "Respiratory",
    outbreakAgent: "COVID-19",
    outbreakBegan: "2024-11-09",
    outbreakAddress: "245 Sunrise Ave, Toronto, ON M4C 1B2",
    lastName: "Patel",
    firstName: "Priya",
    gender: "Female",
    role: "Staff",
    address: "88 Danforth Ave",
    city: "Toronto",
    phone: "647-555-0203",
    email: "p.patel@sunrisegardens.ca",
    buildingUnit: "Floor 3 / Nursing station",
    symptomOnset: "2024-11-12",
    fever: false,
    cough: true,
    sob: false,
    fatigue: true,
    headache: true,
    soreThroat: true,
    myalgia: false,
    chills: false,
    asx: false,
    testingStatus: "Complete",
    testingResult: "Positive",
    classification: "Confirmed",
    currentStatus: "Recovered",
    disposition: "Home isolation",
    comments: "RPN, off work 7 days",
  },
  {
    id: "case-004",
    outbreakId: "ob-001",
    outbreakName: "Sunrise Gardens LTCH",
    outbreakSetting: "LTCH",
    outbreakType: "Respiratory",
    outbreakAgent: "COVID-19",
    outbreakBegan: "2024-11-09",
    outbreakAddress: "245 Sunrise Ave, Toronto, ON M4C 1B2",
    lastName: "Chen",
    firstName: "Wei",
    gender: "Male",
    role: "Staff",
    address: "12 Broadview Ave",
    city: "Toronto",
    phone: "416-555-0304",
    email: "w.chen@sunrisegardens.ca",
    buildingUnit: "Floor 2 / Kitchen",
    symptomOnset: "",
    fever: false,
    cough: false,
    sob: false,
    fatigue: false,
    headache: false,
    soreThroat: false,
    myalgia: false,
    chills: false,
    asx: true,
    testingStatus: "Complete",
    testingResult: "Positive",
    classification: "Confirmed",
    currentStatus: "Recovered",
    disposition: "Home isolation",
    comments: "Asymptomatic — detected via screening",
  },
  {
    id: "case-005",
    outbreakId: "ob-001",
    outbreakName: "Sunrise Gardens LTCH",
    outbreakSetting: "LTCH",
    outbreakType: "Respiratory",
    outbreakAgent: "COVID-19",
    outbreakBegan: "2024-11-09",
    outbreakAddress: "245 Sunrise Ave, Toronto, ON M4C 1B2",
    lastName: "Williams",
    firstName: "Dorothy",
    gender: "Female",
    role: "Resident",
    address: "245 Sunrise Ave",
    city: "Toronto",
    phone: "416-555-0105",
    email: "",
    buildingUnit: "Floor 2 / Room 214",
    symptomOnset: "2024-11-13",
    fever: true,
    cough: false,
    sob: false,
    fatigue: true,
    headache: false,
    soreThroat: false,
    myalgia: false,
    chills: false,
    asx: false,
    testingStatus: "Pending",
    testingResult: "Pending",
    classification: "Probable",
    currentStatus: "Active",
    disposition: "",
    comments: "Awaiting PCR result",
  },
  {
    id: "case-006",
    outbreakId: "ob-001",
    outbreakName: "Sunrise Gardens LTCH",
    outbreakSetting: "LTCH",
    outbreakType: "Respiratory",
    outbreakAgent: "COVID-19",
    outbreakBegan: "2024-11-09",
    outbreakAddress: "245 Sunrise Ave, Toronto, ON M4C 1B2",
    lastName: "Tremblay",
    firstName: "Luc",
    gender: "Male",
    role: "Visitor",
    address: "501 Kingston Rd",
    city: "Toronto",
    phone: "647-555-0406",
    email: "ltremblay@gmail.com",
    buildingUnit: "Floor 3",
    symptomOnset: "2024-11-14",
    fever: false,
    cough: true,
    sob: false,
    fatigue: false,
    headache: true,
    soreThroat: true,
    myalgia: false,
    chills: false,
    asx: false,
    testingStatus: "Declined",
    testingResult: "Unknown",
    classification: "Does Not Meet Definition",
    currentStatus: "Lost to Follow-Up",
    disposition: "LTFU",
    comments: "Unable to reach after initial contact",
  },
  {
    id: "case-007",
    outbreakId: "ob-001",
    outbreakName: "Sunrise Gardens LTCH",
    outbreakSetting: "LTCH",
    outbreakType: "Respiratory",
    outbreakAgent: "COVID-19",
    outbreakBegan: "2024-11-09",
    outbreakAddress: "245 Sunrise Ave, Toronto, ON M4C 1B2",
    lastName: "Nguyen",
    firstName: "Linh",
    gender: "Female",
    role: "Staff",
    address: "77 Gerrard St E",
    city: "Toronto",
    phone: "416-555-0507",
    email: "l.nguyen@sunrisegardens.ca",
    buildingUnit: "Floor 1 / Admin",
    symptomOnset: "2024-11-11",
    fever: true,
    cough: true,
    sob: false,
    fatigue: true,
    headache: true,
    soreThroat: false,
    myalgia: false,
    chills: true,
    asx: false,
    testingStatus: "Complete",
    testingResult: "Negative",
    classification: "Probable",
    currentStatus: "Active",
    disposition: "Home isolation",
    comments: "Staff screening detected symptoms",
  },
  {
    id: "case-008",
    outbreakId: "ob-001",
    outbreakName: "Sunrise Gardens LTCH",
    outbreakSetting: "LTCH",
    outbreakType: "Respiratory",
    outbreakAgent: "COVID-19",
    outbreakBegan: "2024-11-09",
    outbreakAddress: "245 Sunrise Ave, Toronto, ON M4C 1B2",
    lastName: "Kaur",
    firstName: "Aman",
    gender: "Male",
    role: "Resident",
    address: "245 Sunrise Ave",
    city: "Toronto",
    phone: "416-555-0108",
    email: "",
    buildingUnit: "Floor 1 / Room 110",
    symptomOnset: "2024-11-12",
    fever: true,
    cough: false,
    sob: false,
    fatigue: true,
    headache: false,
    soreThroat: false,
    myalgia: true,
    chills: false,
    asx: false,
    testingStatus: "Complete",
    testingResult: "Positive",
    classification: "Confirmed",
    currentStatus: "Active",
    disposition: "Home isolation",
    comments: "Known contact of case in Room 118",
  },
  {
    id: "case-009",
    outbreakId: "ob-002",
    outbreakName: "Fairview Retirement Home",
    outbreakSetting: "Retirement Home",
    outbreakType: "Gastroenteric",
    outbreakAgent: "Norovirus",
    outbreakBegan: "2024-11-08",
    outbreakAddress: "1820 Sheppard Ave E, Toronto, ON M2J 4S1",
    lastName: "Davies",
    firstName: "Eleanor",
    gender: "Female",
    role: "Staff",
    address: "900 Lawrence Ave E",
    city: "Toronto",
    phone: "647-555-0609",
    email: "e.davies@fairviewrh.ca",
    buildingUnit: "Floor 3 / Laundry",
    symptomOnset: "2024-11-13",
    fever: false,
    cough: true,
    sob: false,
    fatigue: true,
    headache: false,
    soreThroat: false,
    myalgia: false,
    chills: false,
    asx: false,
    testingStatus: "Complete",
    testingResult: "Positive",
    classification: "Confirmed",
    currentStatus: "Recovered",
    disposition: "Home isolation",
    comments: "No recent travel",
  },
  {
    id: "case-010",
    outbreakId: "ob-002",
    outbreakName: "Fairview Retirement Home",
    outbreakSetting: "Retirement Home",
    outbreakType: "Gastroenteric",
    outbreakAgent: "Norovirus",
    outbreakBegan: "2024-11-08",
    outbreakAddress: "1820 Sheppard Ave E, Toronto, ON M2J 4S1",
    lastName: "Brown",
    firstName: "Nia",
    gender: "Female",
    role: "Resident",
    address: "1820 Sheppard Ave E",
    city: "Toronto",
    phone: "416-555-0110",
    email: "",
    buildingUnit: "Floor 2 / Room 217",
    symptomOnset: "2024-11-15",
    fever: false,
    cough: false,
    sob: false,
    fatigue: false,
    headache: false,
    soreThroat: false,
    myalgia: false,
    chills: false,
    asx: true,
    testingStatus: "Complete",
    testingResult: "Positive",
    classification: "Confirmed",
    currentStatus: "Recovered",
    disposition: "Home isolation",
    comments: "Asymptomatic, detected during outbreak testing",
  },
  {
    id: "case-011",
    outbreakId: "ob-002",
    outbreakName: "Fairview Retirement Home",
    outbreakSetting: "Retirement Home",
    outbreakType: "Gastroenteric",
    outbreakAgent: "Norovirus",
    outbreakBegan: "2024-11-08",
    outbreakAddress: "1820 Sheppard Ave E, Toronto, ON M2J 4S1",
    lastName: "Morrison",
    firstName: "Liam",
    gender: "Male",
    role: "Resident",
    address: "1820 Sheppard Ave E",
    city: "Toronto",
    phone: "416-555-0111",
    email: "",
    buildingUnit: "Floor 1 / Room 104",
    symptomOnset: "2024-11-15",
    fever: true,
    cough: true,
    sob: false,
    fatigue: true,
    headache: true,
    soreThroat: true,
    myalgia: true,
    chills: true,
    asx: false,
    testingStatus: "Complete",
    testingResult: "Positive",
    classification: "Confirmed",
    currentStatus: "Active",
    disposition: "Hospital transfer",
    comments: "Transferred after rapid deterioration",
  },
];

export const SYMPTOM_KEYS: { key: keyof LinelistCase; label: string }[] = [
  { key: "fever", label: "Fever" },
  { key: "cough", label: "Cough" },
  { key: "sob", label: "SOB" },
  { key: "fatigue", label: "Fatigue" },
  { key: "headache", label: "Headache" },
  { key: "soreThroat", label: "Sore Throat" },
  { key: "myalgia", label: "Myalgia" },
  { key: "chills", label: "Chills" },
  { key: "asx", label: "Asymptomatic" },
];
